project_id = "xwodfkscsdcgpblbnxhd"

[functions.ai-fiscal-agent]
verify_jwt = false

[functions.ai-image-analysis]
verify_jwt = false

[functions.ai-obrify-agent]
verify_jwt = false

[functions.ai-analyze-project]
verify_jwt = false

[functions.ai-compare-projects]
verify_jwt = false