project_id = "xwodfkscsdcgpblbnxhd"

[functions.ai-fiscal-agent]
verify_jwt = false

[functions.ai-image-analysis]
verify_jwt = false

[functions.ai-obrify-agent]
verify_jwt = false

[functions.ai-analyze-project]
verify_jwt = false

[functions.ai-compare-projects]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt-token]
verify_jwt = false

[functions.incompaticheck-agent]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false